name: rattil
description: "Rattil is a modern Quran learning app designed to help users of all ages learn, recite, and understand the Quran with ease. Featuring interactive lessons and a beautiful user experience."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # curved_notification_bar: ^1.0.2
  curved_navigation_bar: ^1.0.6 #latest version
  flutter_svg: ^2.0.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  provider: ^6.0.5
  syncfusion_flutter_pdfviewer: ^24.1.41
  purchases_flutter: ^9.10.0
  purchases_ui_flutter: ^9.10.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.svg
    - assets/quran carousel/banner_1.png
    - assets/quran carousel/banner_2.png
    - assets/quran carousel/banner_3.png
    - assets/pdf/rattil_app_testing.pdf